# Generated by Django 2.2.2 on 2019-08-04 06:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profirl',
            new_name='Profile',
        ),
    ]
